DELETE FROM PROJECT_EMPLOYEES;
DELETE FROM PROJECT;
DELETE FROM PHONE;
DELETE FROM EMPLOYEE;
DELETE FROM ADDRESS;
DELETE FROM DEPARTMENT;

INSERT INTO PROJECT (DTYPE, ID, NAME) VALUES ('DesignProject', 1, 'Neue Website');
INSERT INTO PROJECT (DTYPE, ID, NAME) VALUES ('QualityProject', 2, 'Quality Gate 2');

INSERT INTO DEPARTMENT (ID, NAME) VALUES (1, 'HR');

INSERT INTO ADDRESS (ID, CITY, STATE, STREET, ZIP) VALUES (1, 'Rehag', 'AG', 'Plattenstrasse 26', '5046');
INSERT INTO EMPLOYEE (ID, NAME, SALARY, ADDRESS_ID, BOSS_ID, DEPARTMENT_ID) VALUES (1, 'Ursula Friedman', 95000, 1, null, 1);
INSERT INTO PHONE (ID, PHONENUMBER, TYPE, EMPLOYEE_ID) VALUES (1, '031 333 11 12', 'WORK', 1);

INSERT INTO DEPARTMENT (ID, NAME) VALUES (2, 'IT');

INSERT INTO ADDRESS (ID, CITY, STATE, STREET, ZIP) VALUES (2, 'Fruthwilen', 'ZH', 'Im Sandb�el 55', '8269');
INSERT INTO EMPLOYEE (ID, NAME, SALARY, ADDRESS_ID, BOSS_ID, DEPARTMENT_ID) VALUES (2, 'Hans Boss', 175000, 2, null, 2);
INSERT INTO PHONE (ID, PHONENUMBER, TYPE, EMPLOYEE_ID) VALUES (2, '031 333 11 01', 'WORK', 2);

INSERT INTO ADDRESS (ID, CITY, STATE, STREET, ZIP) VALUES (3, 'Bern', 'BE', 'Rosengasse 1', '3012');
INSERT INTO EMPLOYEE (ID, NAME, SALARY, ADDRESS_ID, BOSS_ID, DEPARTMENT_ID) VALUES (3, 'Peter Muster', 88000, 3, 2, 2);
INSERT INTO PHONE (ID, PHONENUMBER, TYPE, EMPLOYEE_ID) VALUES (3, '044 450 61 34', 'HOME', 3);
INSERT INTO PHONE (ID, PHONENUMBER, TYPE, EMPLOYEE_ID) VALUES (4, '031 333 11 32', 'WORK', 3);

INSERT INTO PROJECT_EMPLOYEES (EMPLOYEES_ID, PROJECTS_ID) VALUES (3, 1);

INSERT INTO ADDRESS (ID, CITY, STATE, STREET, ZIP) VALUES (4, 'Vaugondry', 'VD', 'Via Gabbietta 77', '1423');
INSERT INTO EMPLOYEE (ID, NAME, SALARY, ADDRESS_ID, BOSS_ID, DEPARTMENT_ID) VALUES (4, 'Luca Traugott', 72000, 4, 2, 2);
INSERT INTO PHONE (ID, PHONENUMBER, TYPE, EMPLOYEE_ID) VALUES (5, '024 656 44 65', 'HOME', 4);
INSERT INTO PHONE (ID, PHONENUMBER, TYPE, EMPLOYEE_ID) VALUES (6, '031 333 11 15', 'WORK', 4);

INSERT INTO PROJECT_EMPLOYEES (EMPLOYEES_ID, PROJECTS_ID) VALUES (4, 2);

INSERT INTO ADDRESS (ID, CITY, STATE, STREET, ZIP) VALUES (5, 'Unterstammheim', 'ZH', 'Via Verbano 75', '8476');
INSERT INTO EMPLOYEE (ID, NAME, SALARY, ADDRESS_ID, BOSS_ID, DEPARTMENT_ID) VALUES (5, 'Lea Schulze', 72000, 5, 2, 2);
INSERT INTO PHONE (ID, PHONENUMBER, TYPE, EMPLOYEE_ID) VALUES (7, '052 527 23 11', 'HOME', 5);
INSERT INTO PHONE (ID, PHONENUMBER, TYPE, EMPLOYEE_ID) VALUES (8, '031 333 11 76', 'WORK', 5);

INSERT INTO PROJECT_EMPLOYEES (EMPLOYEES_ID, PROJECTS_ID) VALUES (5, 1);

INSERT INTO ADDRESS (ID, CITY, STATE, STREET, ZIP) VALUES (6, 'Geiss', 'ZH', 'Schliffgasse 64', '6123');
INSERT INTO EMPLOYEE (ID, NAME, SALARY, ADDRESS_ID, BOSS_ID, DEPARTMENT_ID) VALUES (6, 'Felix Beyer', 79000, 6, 2, 2);
