ALTER TABLE employee
    ADD COLUMN VERSION INTEGER DEFAULT 0;

ALTER TABLE employee
    ADD COLUMN CREATED_DATE TIMESTAMP;

ALTER TABLE employee
    ADD COLUMN LAST_MODIFIED_DATE TIMESTAMP;

ALTER TABLE address
    ADD COLUMN VERSION INTEGER DEFAULT 0;

ALTER TABLE address
    ADD COLUMN CREATED_DATE TIMESTAMP;

ALTER TABLE address
    ADD COLUMN LAST_MODIFIED_DATE TIMESTAMP;

ALTER TABLE department
    ADD COLUMN VERSION INTEGER DEFAULT 0;

ALTER TABLE department
    ADD COLUMN CREATED_DATE TIMESTAMP;

ALTER TABLE department
    ADD COLUMN LAST_MODIFIED_DATE TIMESTAMP;

ALTER TABLE phone
    ADD COLUMN VERSION INTEGER DEFAULT 0;

ALTER TABLE phone
    ADD COLUMN CREATED_DATE TIMESTAMP;

ALTER TABLE phone
    ADD COLUMN LAST_MODIFIED_DATE TIMESTAMP;

ALTER TABLE project
    ADD COLUMN VERSION INTEGER DEFAULT 0;

ALTER TABLE project
    ADD COLUMN CREATED_DATE TIMESTAMP;

ALTER TABLE project
    ADD COLUMN LAST_MODIFIED_DATE TIMESTAMP;